create role anon;
create role authenticated;
create table public.workers (worker_id text primary key, worker_name text);
insert into public.workers values ('tester', 'Tester');
create function public.flexcon_require_active_worker(p_worker_id text) returns void language plpgsql as $$
begin
  if p_worker_id <> 'tester' then raise exception 'unauthorized'; end if;
end;
$$;
create table public.flexcon_authorizations (id uuid primary key default gen_random_uuid(), authorization_no text, full_name text, prefecture text);
create table public.flexcon_inspection_options (id uuid primary key default gen_random_uuid(), option_type text, name text, active boolean default true, sort_order integer default 0, created_at timestamptz default now());
create table public.flexcon_inspection_weights (weight_type text primary key, weight_kg integer);
create table public.flexcon_inspection_registrations (
  id uuid primary key default gen_random_uuid(), registration_no bigint generated by default as identity unique,
  authorization_id uuid references public.flexcon_authorizations, warehouse_id uuid references public.flexcon_inspection_options,
  settlement_no text, created_by_worker_id text, created_at timestamptz default now()
);
create table public.flexcon_inspection_flexcons (
  id uuid primary key default gen_random_uuid(), registration_id uuid references public.flexcon_inspection_registrations,
  authorization_id uuid references public.flexcon_authorizations, fiscal_year integer, purchase_date date,
  inspection_date date, inspector_name text, inspection_location text, record_kind text, flexcon_no integer,
  lot_number text unique, brand text, quantity_kg integer, grade text, reason text, moisture numeric,
  moisture_values numeric[] default '{}', created_by_worker_id text, updated_by_worker_id text,
  created_at timestamptz default now(), updated_at timestamptz default now(), unique(authorization_id, record_kind, flexcon_no)
);
create table public.flexcon_inspection_paper_bags (
  id uuid primary key default gen_random_uuid(), registration_id uuid references public.flexcon_inspection_registrations,
  authorization_id uuid references public.flexcon_authorizations, fiscal_year integer, purchase_date date,
  inspection_date date, inspector_name text, inspection_location text, brand text, bag_count integer,
  grade text, reason text, moisture numeric, moisture_values numeric[] default '{}',
  created_by_worker_id text, updated_by_worker_id text, created_at timestamptz default now(), updated_at timestamptz default now()
);
insert into public.flexcon_authorizations (id, authorization_no, full_name, prefecture) values
  ('00000000-0000-0000-0000-000000000001','1','Producer','青森県'),
  ('00000000-0000-0000-0000-000000000002','2','New Producer','青森県');
insert into public.flexcon_inspection_options (id,option_type,name) values
  ('00000000-0000-0000-0000-000000000011','warehouse','A'),
  ('00000000-0000-0000-0000-000000000012','warehouse','B'),
  ('00000000-0000-0000-0000-000000000013','warehouse','倉庫未設定'),
  ('00000000-0000-0000-0000-000000000014','location','A'),
  ('00000000-0000-0000-0000-000000000015','location','B');
insert into public.flexcon_inspection_registrations (id,authorization_id,warehouse_id,settlement_no,created_by_worker_id) values
  ('00000000-0000-0000-0000-000000000021','00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000011','OLD-A','tester'),
  ('00000000-0000-0000-0000-000000000022','00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000012','OLD-B','tester');
insert into public.flexcon_inspection_flexcons (registration_id,authorization_id,fiscal_year,purchase_date,inspection_date,inspection_location,record_kind,flexcon_no,lot_number,brand,quantity_kg,grade,created_by_worker_id,updated_by_worker_id) values
  ('00000000-0000-0000-0000-000000000021','00000000-0000-0000-0000-000000000001',8,'2026-09-01','2026-09-02','A','standard',1,'20260001001','Rice',1020,'1等','tester','tester'),
  ('00000000-0000-0000-0000-000000000022','00000000-0000-0000-0000-000000000001',8,'2026-09-03',null,'B','standard',2,'20260001002','Rice',1020,null,'tester','tester');
insert into public.flexcon_inspection_paper_bags (registration_id,authorization_id,fiscal_year,purchase_date,inspection_location,brand,bag_count,created_by_worker_id,updated_by_worker_id) values
  ('00000000-0000-0000-0000-000000000022','00000000-0000-0000-0000-000000000001',8,'2026-09-03','B','Rice',10,'tester','tester');
create view public.flexcon_inventory_ledger_base as
select 'inspection-flexcon:' || d.id::text as id, null::bigint as registration_order,
  'inspection_flexcon'::text as source_type, 'inbound'::text as movement_type,
  d.purchase_date as movement_date, 'Tester'::text as worker_name, 'Producer'::text as producer_name,
  ''::text as settlement_no, '青森県'::text as origin, d.brand as product_name,
  coalesce(d.grade,'検査前') as grade, case when d.record_kind='bulk' then d.quantity_kg else 1 end::numeric as quantity,
  case when d.record_kind='bulk' then 'kg' else '本' end as unit, null::uuid as from_warehouse_id,
  r.warehouse_id as to_warehouse_id, '検査記録'::text as movement_from, w.name as movement_to, d.created_at, null::numeric as purchase_price
from public.flexcon_inspection_flexcons d join public.flexcon_inspection_registrations r on r.id=d.registration_id
join public.flexcon_inspection_options w on w.id=r.warehouse_id
union all
select 'inspection-paper:' || d.id::text, null::bigint, 'inspection_paper_bag','inbound',d.purchase_date,
  'Tester','Producer','','青森県',d.brand,coalesce(d.grade,'検査前'),d.bag_count::numeric,'袋',null::uuid,
  r.warehouse_id,'検査記録',w.name,d.created_at,null::numeric
from public.flexcon_inspection_paper_bags d join public.flexcon_inspection_registrations r on r.id=d.registration_id
join public.flexcon_inspection_options w on w.id=r.warehouse_id;
create view public.flexcon_inventory_ledger as select base.*,null::integer as crop_year from public.flexcon_inventory_ledger_base base;
create view public.flexcon_inventory_balances_base as
select base.to_warehouse_id as warehouse_id,base.movement_to as warehouse_name,base.origin,base.product_name,base.grade,base.unit,
sum(base.quantity)::numeric(14,3) as quantity from public.flexcon_inventory_ledger_base base
group by base.to_warehouse_id,base.movement_to,base.origin,base.product_name,base.grade,base.unit;
create view public.flexcon_inventory_balances as select * from public.flexcon_inventory_balances_base;
create view public.flexcon_inventory_balances_by_crop_year as select base.*,8 as crop_year from public.flexcon_inventory_balances_base base;
