-- 生産者詳細で追加した1回分を登録No.付きで保持し、検査記録一覧に表示します。
-- 202609070006_mixed_flexcon_shipping.sql の実行後に適用してください。

begin;

create table if not exists public.flexcon_inspection_registrations (
  id uuid primary key default gen_random_uuid(),
  registration_no bigint generated by default as identity unique,
  authorization_id uuid not null references public.flexcon_authorizations(id) on delete cascade,
  created_by_worker_id text not null references public.workers(worker_id),
  created_at timestamptz not null default now()
);

alter table public.flexcon_inspection_flexcons
  add column if not exists registration_id uuid
  references public.flexcon_inspection_registrations(id) on delete cascade;

alter table public.flexcon_inspection_paper_bags
  add column if not exists registration_id uuid
  references public.flexcon_inspection_registrations(id) on delete cascade;

do $$
declare
  v_group record;
  v_registration_id uuid;
begin
  for v_group in
    select source.authorization_id, source.created_by_worker_id, source.created_at
    from (
      select flexcon.authorization_id, flexcon.created_by_worker_id, flexcon.created_at
      from public.flexcon_inspection_flexcons as flexcon
      where flexcon.registration_id is null
      union all
      select paper.authorization_id, paper.created_by_worker_id, paper.created_at
      from public.flexcon_inspection_paper_bags as paper
      where paper.registration_id is null
    ) as source
    group by source.authorization_id, source.created_by_worker_id, source.created_at
    order by source.created_at, source.authorization_id
  loop
    insert into public.flexcon_inspection_registrations (
      authorization_id, created_by_worker_id, created_at
    ) values (
      v_group.authorization_id, v_group.created_by_worker_id, v_group.created_at
    ) returning id into v_registration_id;

    update public.flexcon_inspection_flexcons
    set registration_id = v_registration_id
    where registration_id is null
      and authorization_id = v_group.authorization_id
      and created_by_worker_id = v_group.created_by_worker_id
      and created_at = v_group.created_at;

    update public.flexcon_inspection_paper_bags
    set registration_id = v_registration_id
    where registration_id is null
      and authorization_id = v_group.authorization_id
      and created_by_worker_id = v_group.created_by_worker_id
      and created_at = v_group.created_at;
  end loop;
end;
$$;

alter table public.flexcon_inspection_flexcons
  alter column registration_id set not null;
alter table public.flexcon_inspection_paper_bags
  alter column registration_id set not null;

create index if not exists flexcon_inspection_flexcons_registration_idx
  on public.flexcon_inspection_flexcons (registration_id, flexcon_no);
create index if not exists flexcon_inspection_paper_bags_registration_idx
  on public.flexcon_inspection_paper_bags (registration_id, created_at);
create index if not exists flexcon_inspection_registrations_order_idx
  on public.flexcon_inspection_registrations (registration_no);

alter table public.flexcon_inspection_registrations enable row level security;
drop policy if exists flexcon_read_inspection_registrations
  on public.flexcon_inspection_registrations;
create policy flexcon_read_inspection_registrations
  on public.flexcon_inspection_registrations
  for select to anon, authenticated using (true);
grant select on table public.flexcon_inspection_registrations to anon, authenticated;

drop function if exists public.flexcon_add_inspection_group(
  text, uuid, integer, date, date, text, text, integer, integer, integer, integer
);

create function public.flexcon_add_inspection_group(
  p_worker_id text,
  p_authorization_id uuid,
  p_fiscal_year integer,
  p_purchase_date date,
  p_inspection_date date,
  p_inspection_location text,
  p_brand text,
  p_flexcon_count integer,
  p_paper_bag_count integer,
  p_flexcon_quantity_kg integer,
  p_bulk_quantity_kg integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_authorization_no text;
  v_registration_id uuid;
  v_registration_no bigint;
  v_next_flexcon_no integer;
  v_index integer;
  v_lot_number text;
  v_total_flexcons integer;
  v_flexcon_inserted integer := 0;
  v_bulk_inserted integer := 0;
  v_paper_inserted integer := 0;
begin
  perform public.flexcon_require_active_worker(p_worker_id);

  select auth_record.authorization_no
  into v_authorization_no
  from public.flexcon_authorizations as auth_record
  where auth_record.id = p_authorization_id
  for update;

  if v_authorization_no is null then raise exception '委任状情報が見つかりません。'; end if;
  if v_authorization_no !~ '^[0-9]{1,4}$' then raise exception '委任状№は4桁以内の数字にしてください。'; end if;
  if p_fiscal_year is null or p_fiscal_year not between 1 and 99 then
    raise exception '年度は1から99の整数で入力してください。';
  end if;
  if p_purchase_date is null then raise exception '仕入日を入力してください。'; end if;
  if char_length(btrim(coalesce(p_brand, ''))) = 0 then raise exception '銘柄を選択してください。'; end if;
  if coalesce(p_flexcon_count, 0) < 0
     or coalesce(p_paper_bag_count, 0) < 0
     or coalesce(p_bulk_quantity_kg, 0) < 0 then
    raise exception 'フレコン本数、紙袋数、バラは0以上で入力してください。';
  end if;
  if coalesce(p_flexcon_count, 0) = 0
     and coalesce(p_paper_bag_count, 0) = 0
     and coalesce(p_bulk_quantity_kg, 0) = 0 then
    raise exception 'フレコン本数、紙袋数、バラのいずれかを入力してください。';
  end if;
  if coalesce(p_flexcon_count, 0) > 0
     and (p_flexcon_quantity_kg is null or p_flexcon_quantity_kg <= 0) then
    raise exception 'フレコンの量目が正しくありません。';
  end if;

  select coalesce(max(flexcon.flexcon_no), 0) + 1
  into v_next_flexcon_no
  from public.flexcon_inspection_flexcons as flexcon
  where flexcon.authorization_id = p_authorization_id;

  v_total_flexcons := coalesce(p_flexcon_count, 0)
    + case when coalesce(p_bulk_quantity_kg, 0) > 0 then 1 else 0 end;
  if v_next_flexcon_no + v_total_flexcons - 1 > 999 then
    raise exception 'フレコン№が999を超えるため追加できません。';
  end if;

  insert into public.flexcon_inspection_registrations (
    authorization_id, created_by_worker_id
  ) values (
    p_authorization_id, p_worker_id
  ) returning id, registration_no into v_registration_id, v_registration_no;

  for v_index in 1..coalesce(p_flexcon_count, 0) loop
    v_lot_number := lpad((p_fiscal_year + 2018)::text, 4, '0')
      || lpad(v_authorization_no, 4, '0')
      || lpad(v_next_flexcon_no::text, 3, '0');
    insert into public.flexcon_inspection_flexcons (
      registration_id, authorization_id, fiscal_year, purchase_date, inspection_date,
      inspection_location, flexcon_no, lot_number, brand, quantity_kg,
      moisture_values, created_by_worker_id, updated_by_worker_id
    ) values (
      v_registration_id, p_authorization_id, p_fiscal_year, p_purchase_date,
      p_inspection_date, nullif(btrim(p_inspection_location), ''), v_next_flexcon_no,
      v_lot_number, btrim(p_brand), p_flexcon_quantity_kg, '{}'::numeric[],
      p_worker_id, p_worker_id
    );
    v_next_flexcon_no := v_next_flexcon_no + 1;
    v_flexcon_inserted := v_flexcon_inserted + 1;
  end loop;

  if coalesce(p_bulk_quantity_kg, 0) > 0 then
    v_lot_number := lpad((p_fiscal_year + 2018)::text, 4, '0')
      || lpad(v_authorization_no, 4, '0')
      || lpad(v_next_flexcon_no::text, 3, '0');
    insert into public.flexcon_inspection_flexcons (
      registration_id, authorization_id, fiscal_year, purchase_date, inspection_date,
      inspection_location, flexcon_no, lot_number, brand, quantity_kg,
      moisture_values, created_by_worker_id, updated_by_worker_id
    ) values (
      v_registration_id, p_authorization_id, p_fiscal_year, p_purchase_date,
      p_inspection_date, nullif(btrim(p_inspection_location), ''), v_next_flexcon_no,
      v_lot_number, btrim(p_brand), p_bulk_quantity_kg, '{}'::numeric[],
      p_worker_id, p_worker_id
    );
    v_bulk_inserted := 1;
    v_flexcon_inserted := v_flexcon_inserted + 1;
  end if;

  if coalesce(p_paper_bag_count, 0) > 0 then
    insert into public.flexcon_inspection_paper_bags (
      registration_id, authorization_id, fiscal_year, purchase_date, inspection_date,
      inspection_location, brand, bag_count, moisture_values,
      created_by_worker_id, updated_by_worker_id
    ) values (
      v_registration_id, p_authorization_id, p_fiscal_year, p_purchase_date,
      p_inspection_date, nullif(btrim(p_inspection_location), ''), btrim(p_brand),
      p_paper_bag_count, '{}'::numeric[], p_worker_id, p_worker_id
    );
    v_paper_inserted := 1;
  end if;

  return jsonb_build_object(
    'registration_no', v_registration_no,
    'flexcons_inserted', v_flexcon_inserted,
    'bulk_flexcons_inserted', v_bulk_inserted,
    'paper_rows_inserted', v_paper_inserted
  );
end;
$$;

create or replace function public.flexcon_split_inspection_paper_bags(
  p_worker_id text,
  p_paper_bag_id uuid,
  p_first_bag_count integer,
  p_second_bag_count integer
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source public.flexcon_inspection_paper_bags%rowtype;
  v_new_id uuid;
begin
  perform public.flexcon_require_active_worker(p_worker_id);

  select * into v_source
  from public.flexcon_inspection_paper_bags
  where id = p_paper_bag_id
  for update;

  if v_source.id is null then raise exception '分割する紙袋検査記録が見つかりません。'; end if;
  if p_first_bag_count is null or p_first_bag_count <= 0
     or p_second_bag_count is null or p_second_bag_count <= 0 then
    raise exception '分割後の袋数はどちらも1以上で入力してください。';
  end if;
  if p_first_bag_count + p_second_bag_count <> v_source.bag_count then
    raise exception '分割後の合計を元の袋数に合わせてください。';
  end if;

  update public.flexcon_inspection_paper_bags
  set bag_count = p_first_bag_count,
      updated_by_worker_id = p_worker_id,
      updated_at = now()
  where id = v_source.id;

  insert into public.flexcon_inspection_paper_bags (
    registration_id, authorization_id, fiscal_year, purchase_date, inspection_date,
    inspector_name, inspection_location, brand, bag_count, grade, reason, moisture,
    moisture_values, created_by_worker_id, updated_by_worker_id
  ) values (
    v_source.registration_id, v_source.authorization_id, v_source.fiscal_year,
    v_source.purchase_date, v_source.inspection_date, v_source.inspector_name,
    v_source.inspection_location, v_source.brand, p_second_bag_count, v_source.grade,
    v_source.reason, v_source.moisture, v_source.moisture_values,
    p_worker_id, p_worker_id
  ) returning id into v_new_id;

  return v_new_id;
end;
$$;

revoke all on function public.flexcon_add_inspection_group(
  text, uuid, integer, date, date, text, text, integer, integer, integer, integer
) from public;
revoke all on function public.flexcon_split_inspection_paper_bags(
  text, uuid, integer, integer
) from public;
grant execute on function public.flexcon_add_inspection_group(
  text, uuid, integer, date, date, text, text, integer, integer, integer, integer
) to anon, authenticated;
grant execute on function public.flexcon_split_inspection_paper_bags(
  text, uuid, integer, integer
) to anon, authenticated;

commit;
